# Generated by Django 4.2.6 on 2023-10-16 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='backend.image', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='LanguageProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='backend.language', verbose_name='Язык')),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Языки',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(db_index=True, verbose_name='Возраст')),
                ('city', models.CharField(db_index=True, max_length=168, verbose_name='Город')),
                ('description', models.TextField(verbose_name='О себе')),
                ('gender', models.CharField(db_index=True, max_length=10, verbose_name='Пол')),
                ('children', models.BooleanField(verbose_name='Есть дети?')),
                ('education', models.CharField(max_length=150, verbose_name='Образование')),
                ('profession', models.CharField(max_length=50, verbose_name='Должность на работе')),
                ('alcohol', models.BooleanField(verbose_name='Алкоголь')),
                ('sigarettes', models.BooleanField(verbose_name='Сигареты')),
                ('horoscope', models.CharField(max_length=25, verbose_name='Знак по гороскопу')),
                ('target', models.CharField(max_length=35, verbose_name='Цель')),
                ('images', models.ManyToManyField(through='backend.ImageProfile', to='backend.image', verbose_name='Фото')),
                ('languages', models.ManyToManyField(through='backend.LanguageProfile', to='backend.language', verbose_name='Языки')),
            ],
        ),
        migrations.CreateModel(
            name='TagProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='backend.profile', verbose_name='Анкета пользователя')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='backend.tag', verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.RemoveField(
            model_name='languageuser',
            name='language',
        ),
        migrations.RemoveField(
            model_name='languageuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='taguser',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='taguser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='advuser',
            name='age',
        ),
        migrations.RemoveField(
            model_name='advuser',
            name='alcohol',
        ),
        migrations.RemoveField(
            model_name='advuser',
            name='children',
        ),
        migrations.RemoveField(
            model_name='advuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='advuser',
            name='description',
        ),
        migrations.RemoveField(
            model_name='advuser',
            name='education',
        ),
        migrations.RemoveField(
            model_name='advuser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='advuser',
            name='horoscope',
        ),
        migrations.RemoveField(
            model_name='advuser',
            name='images',
        ),
        migrations.RemoveField(
            model_name='advuser',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='advuser',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='advuser',
            name='sigarettes',
        ),
        migrations.RemoveField(
            model_name='advuser',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='advuser',
            name='target',
        ),
        migrations.DeleteModel(
            name='ImageUser',
        ),
        migrations.DeleteModel(
            name='LanguageUser',
        ),
        migrations.DeleteModel(
            name='TagUser',
        ),
        migrations.AddField(
            model_name='profile',
            name='tags',
            field=models.ManyToManyField(through='backend.TagProfile', to='backend.tag', verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='languageprofile',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='backend.profile', verbose_name='Анкета пользователя'),
        ),
        migrations.AddField(
            model_name='imageprofile',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='backend.profile', verbose_name='Анкета пользователя'),
        ),
    ]
