# Generated by Django 4.2.6 on 2023-10-16 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_imageprofile_languageprofile_profile_tagprofile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='sigarettes',
            new_name='smoke',
        ),
    ]
