# Generated by Django 4.2.6 on 2023-10-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_sigarettes_profile_smoke'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='alcohol',
            field=models.BooleanField(blank=True, null=True, verbose_name='Алкоголь'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='children',
            field=models.BooleanField(blank=True, null=True, verbose_name='Есть дети?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='horoscope',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Знак по гороскопу'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='languages',
            field=models.ManyToManyField(blank=True, null=True, through='backend.LanguageProfile', to='backend.language', verbose_name='Языки'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profession',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Должность на работе'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='smoke',
            field=models.BooleanField(blank=True, null=True, verbose_name='Курение'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, through='backend.TagProfile', to='backend.tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='target',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Цель'),
        ),
    ]
