# Generated by Django 4.2.6 on 2023-10-16 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_profile_alcohol_alter_profile_children_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Фото', 'verbose_name_plural': 'Фото'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Анкета', 'verbose_name_plural': 'Анкеты'},
        ),
    ]
