# Generated by Django 4.2.6 on 2023-10-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_image_options_alter_profile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='languages',
            field=models.ManyToManyField(through='backend.LanguageProfile', to='backend.language', verbose_name='Языки'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tags',
            field=models.ManyToManyField(through='backend.TagProfile', to='backend.tag', verbose_name='Теги'),
        ),
    ]
