# Generated by Django 4.2.6 on 2023-10-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_profile_languages_alter_profile_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Андрей', max_length=20, verbose_name='Имя'),
            preserve_default=False,
        ),
    ]
